/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AppVehiclesIndexRouteImport } from './routes/app/vehicles/index'
import { Route as AppReservationsIndexRouteImport } from './routes/app/reservations/index'
import { Route as AppRentalsIndexRouteImport } from './routes/app/rentals/index'
import { Route as AppCustomersIndexRouteImport } from './routes/app/customers/index'
import { Route as AppVehiclesCreateRouteImport } from './routes/app/vehicles/create'
import { Route as AppVehiclesIdRouteImport } from './routes/app/vehicles/$id'
import { Route as AppReservationsCreateRouteImport } from './routes/app/reservations/create'
import { Route as AppReservationsIdRouteImport } from './routes/app/reservations/$id'
import { Route as AppRentalsInitializeRouteImport } from './routes/app/rentals/initialize'
import { Route as AppRentalsIdRouteImport } from './routes/app/rentals/$id'
import { Route as AppCustomersCreateRouteImport } from './routes/app/customers/create'
import { Route as AppCustomersIdRouteImport } from './routes/app/customers/$id'
import { Route as AppVehiclesIdIndexRouteImport } from './routes/app/vehicles/$id/index'
import { Route as AppRentalsIdIndexRouteImport } from './routes/app/rentals/$id/index'
import { Route as AppVehiclesIdReservationsRouteImport } from './routes/app/vehicles/$id/reservations'
import { Route as AppVehiclesIdRentalsRouteImport } from './routes/app/vehicles/$id/rentals'
import { Route as AppVehiclesIdMaintenanceRouteImport } from './routes/app/vehicles/$id/maintenance'
import { Route as AppVehiclesIdExpensesRouteImport } from './routes/app/vehicles/$id/expenses'
import { Route as AppRentalsIdPaymentsRouteImport } from './routes/app/rentals/$id/payments'
import { Route as AppRentalsIdDocumentsRouteImport } from './routes/app/rentals/$id/documents'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiclesIndexRoute = AppVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsIndexRoute = AppReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalsIndexRoute = AppRentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVehiclesCreateRoute = AppVehiclesCreateRouteImport.update({
  id: '/vehicles/create',
  path: '/vehicles/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVehiclesIdRoute = AppVehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsCreateRoute = AppReservationsCreateRouteImport.update({
  id: '/reservations/create',
  path: '/reservations/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsIdRoute = AppReservationsIdRouteImport.update({
  id: '/reservations/$id',
  path: '/reservations/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalsInitializeRoute = AppRentalsInitializeRouteImport.update({
  id: '/rentals/initialize',
  path: '/rentals/initialize',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalsIdRoute = AppRentalsIdRouteImport.update({
  id: '/rentals/$id',
  path: '/rentals/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersCreateRoute = AppCustomersCreateRouteImport.update({
  id: '/customers/create',
  path: '/customers/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVehiclesIdIndexRoute = AppVehiclesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppRentalsIdIndexRoute = AppRentalsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRentalsIdRoute,
} as any)
const AppVehiclesIdReservationsRoute =
  AppVehiclesIdReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AppVehiclesIdRoute,
  } as any)
const AppVehiclesIdRentalsRoute = AppVehiclesIdRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppVehiclesIdMaintenanceRoute =
  AppVehiclesIdMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AppVehiclesIdRoute,
  } as any)
const AppVehiclesIdExpensesRoute = AppVehiclesIdExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppRentalsIdPaymentsRoute = AppRentalsIdPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRentalsIdRoute,
} as any)
const AppRentalsIdDocumentsRoute = AppRentalsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRentalsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/rentals/$id': typeof AppRentalsIdRouteWithChildren
  '/app/rentals/initialize': typeof AppRentalsInitializeRoute
  '/app/reservations/$id': typeof AppReservationsIdRoute
  '/app/reservations/create': typeof AppReservationsCreateRoute
  '/app/vehicles/$id': typeof AppVehiclesIdRouteWithChildren
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/rentals': typeof AppRentalsIndexRoute
  '/app/reservations': typeof AppReservationsIndexRoute
  '/app/vehicles': typeof AppVehiclesIndexRoute
  '/app/rentals/$id/documents': typeof AppRentalsIdDocumentsRoute
  '/app/rentals/$id/payments': typeof AppRentalsIdPaymentsRoute
  '/app/vehicles/$id/expenses': typeof AppVehiclesIdExpensesRoute
  '/app/vehicles/$id/maintenance': typeof AppVehiclesIdMaintenanceRoute
  '/app/vehicles/$id/rentals': typeof AppVehiclesIdRentalsRoute
  '/app/vehicles/$id/reservations': typeof AppVehiclesIdReservationsRoute
  '/app/rentals/$id/': typeof AppRentalsIdIndexRoute
  '/app/vehicles/$id/': typeof AppVehiclesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/rentals/initialize': typeof AppRentalsInitializeRoute
  '/app/reservations/$id': typeof AppReservationsIdRoute
  '/app/reservations/create': typeof AppReservationsCreateRoute
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/rentals': typeof AppRentalsIndexRoute
  '/app/reservations': typeof AppReservationsIndexRoute
  '/app/vehicles': typeof AppVehiclesIndexRoute
  '/app/rentals/$id/documents': typeof AppRentalsIdDocumentsRoute
  '/app/rentals/$id/payments': typeof AppRentalsIdPaymentsRoute
  '/app/vehicles/$id/expenses': typeof AppVehiclesIdExpensesRoute
  '/app/vehicles/$id/maintenance': typeof AppVehiclesIdMaintenanceRoute
  '/app/vehicles/$id/rentals': typeof AppVehiclesIdRentalsRoute
  '/app/vehicles/$id/reservations': typeof AppVehiclesIdReservationsRoute
  '/app/rentals/$id': typeof AppRentalsIdIndexRoute
  '/app/vehicles/$id': typeof AppVehiclesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/rentals/$id': typeof AppRentalsIdRouteWithChildren
  '/app/rentals/initialize': typeof AppRentalsInitializeRoute
  '/app/reservations/$id': typeof AppReservationsIdRoute
  '/app/reservations/create': typeof AppReservationsCreateRoute
  '/app/vehicles/$id': typeof AppVehiclesIdRouteWithChildren
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/rentals/': typeof AppRentalsIndexRoute
  '/app/reservations/': typeof AppReservationsIndexRoute
  '/app/vehicles/': typeof AppVehiclesIndexRoute
  '/app/rentals/$id/documents': typeof AppRentalsIdDocumentsRoute
  '/app/rentals/$id/payments': typeof AppRentalsIdPaymentsRoute
  '/app/vehicles/$id/expenses': typeof AppVehiclesIdExpensesRoute
  '/app/vehicles/$id/maintenance': typeof AppVehiclesIdMaintenanceRoute
  '/app/vehicles/$id/rentals': typeof AppVehiclesIdRentalsRoute
  '/app/vehicles/$id/reservations': typeof AppVehiclesIdReservationsRoute
  '/app/rentals/$id/': typeof AppRentalsIdIndexRoute
  '/app/vehicles/$id/': typeof AppVehiclesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/'
    | '/demo'
    | '/app/customers/$id'
    | '/app/customers/create'
    | '/app/rentals/$id'
    | '/app/rentals/initialize'
    | '/app/reservations/$id'
    | '/app/reservations/create'
    | '/app/vehicles/$id'
    | '/app/vehicles/create'
    | '/app/customers'
    | '/app/rentals'
    | '/app/reservations'
    | '/app/vehicles'
    | '/app/rentals/$id/documents'
    | '/app/rentals/$id/payments'
    | '/app/vehicles/$id/expenses'
    | '/app/vehicles/$id/maintenance'
    | '/app/vehicles/$id/rentals'
    | '/app/vehicles/$id/reservations'
    | '/app/rentals/$id/'
    | '/app/vehicles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/signin'
    | '/auth/signup'
    | '/app'
    | '/demo'
    | '/app/customers/$id'
    | '/app/customers/create'
    | '/app/rentals/initialize'
    | '/app/reservations/$id'
    | '/app/reservations/create'
    | '/app/vehicles/create'
    | '/app/customers'
    | '/app/rentals'
    | '/app/reservations'
    | '/app/vehicles'
    | '/app/rentals/$id/documents'
    | '/app/rentals/$id/payments'
    | '/app/vehicles/$id/expenses'
    | '/app/vehicles/$id/maintenance'
    | '/app/vehicles/$id/rentals'
    | '/app/vehicles/$id/reservations'
    | '/app/rentals/$id'
    | '/app/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/'
    | '/demo/'
    | '/app/customers/$id'
    | '/app/customers/create'
    | '/app/rentals/$id'
    | '/app/rentals/initialize'
    | '/app/reservations/$id'
    | '/app/reservations/create'
    | '/app/vehicles/$id'
    | '/app/vehicles/create'
    | '/app/customers/'
    | '/app/rentals/'
    | '/app/reservations/'
    | '/app/vehicles/'
    | '/app/rentals/$id/documents'
    | '/app/rentals/$id/payments'
    | '/app/vehicles/$id/expenses'
    | '/app/vehicles/$id/maintenance'
    | '/app/vehicles/$id/rentals'
    | '/app/vehicles/$id/reservations'
    | '/app/rentals/$id/'
    | '/app/vehicles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vehicles/': {
      id: '/app/vehicles/'
      path: '/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AppVehiclesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reservations/': {
      id: '/app/reservations/'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rentals/': {
      id: '/app/rentals/'
      path: '/rentals'
      fullPath: '/app/rentals'
      preLoaderRoute: typeof AppRentalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vehicles/create': {
      id: '/app/vehicles/create'
      path: '/vehicles/create'
      fullPath: '/app/vehicles/create'
      preLoaderRoute: typeof AppVehiclesCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vehicles/$id': {
      id: '/app/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/app/vehicles/$id'
      preLoaderRoute: typeof AppVehiclesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reservations/create': {
      id: '/app/reservations/create'
      path: '/reservations/create'
      fullPath: '/app/reservations/create'
      preLoaderRoute: typeof AppReservationsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reservations/$id': {
      id: '/app/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/app/reservations/$id'
      preLoaderRoute: typeof AppReservationsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rentals/initialize': {
      id: '/app/rentals/initialize'
      path: '/rentals/initialize'
      fullPath: '/app/rentals/initialize'
      preLoaderRoute: typeof AppRentalsInitializeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rentals/$id': {
      id: '/app/rentals/$id'
      path: '/rentals/$id'
      fullPath: '/app/rentals/$id'
      preLoaderRoute: typeof AppRentalsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers/create': {
      id: '/app/customers/create'
      path: '/customers/create'
      fullPath: '/app/customers/create'
      preLoaderRoute: typeof AppCustomersCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers/$id': {
      id: '/app/customers/$id'
      path: '/customers/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vehicles/$id/': {
      id: '/app/vehicles/$id/'
      path: '/'
      fullPath: '/app/vehicles/$id/'
      preLoaderRoute: typeof AppVehiclesIdIndexRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/rentals/$id/': {
      id: '/app/rentals/$id/'
      path: '/'
      fullPath: '/app/rentals/$id/'
      preLoaderRoute: typeof AppRentalsIdIndexRouteImport
      parentRoute: typeof AppRentalsIdRoute
    }
    '/app/vehicles/$id/reservations': {
      id: '/app/vehicles/$id/reservations'
      path: '/reservations'
      fullPath: '/app/vehicles/$id/reservations'
      preLoaderRoute: typeof AppVehiclesIdReservationsRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/vehicles/$id/rentals': {
      id: '/app/vehicles/$id/rentals'
      path: '/rentals'
      fullPath: '/app/vehicles/$id/rentals'
      preLoaderRoute: typeof AppVehiclesIdRentalsRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/vehicles/$id/maintenance': {
      id: '/app/vehicles/$id/maintenance'
      path: '/maintenance'
      fullPath: '/app/vehicles/$id/maintenance'
      preLoaderRoute: typeof AppVehiclesIdMaintenanceRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/vehicles/$id/expenses': {
      id: '/app/vehicles/$id/expenses'
      path: '/expenses'
      fullPath: '/app/vehicles/$id/expenses'
      preLoaderRoute: typeof AppVehiclesIdExpensesRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/rentals/$id/payments': {
      id: '/app/rentals/$id/payments'
      path: '/payments'
      fullPath: '/app/rentals/$id/payments'
      preLoaderRoute: typeof AppRentalsIdPaymentsRouteImport
      parentRoute: typeof AppRentalsIdRoute
    }
    '/app/rentals/$id/documents': {
      id: '/app/rentals/$id/documents'
      path: '/documents'
      fullPath: '/app/rentals/$id/documents'
      preLoaderRoute: typeof AppRentalsIdDocumentsRouteImport
      parentRoute: typeof AppRentalsIdRoute
    }
  }
}

interface AppRentalsIdRouteChildren {
  AppRentalsIdDocumentsRoute: typeof AppRentalsIdDocumentsRoute
  AppRentalsIdPaymentsRoute: typeof AppRentalsIdPaymentsRoute
  AppRentalsIdIndexRoute: typeof AppRentalsIdIndexRoute
}

const AppRentalsIdRouteChildren: AppRentalsIdRouteChildren = {
  AppRentalsIdDocumentsRoute: AppRentalsIdDocumentsRoute,
  AppRentalsIdPaymentsRoute: AppRentalsIdPaymentsRoute,
  AppRentalsIdIndexRoute: AppRentalsIdIndexRoute,
}

const AppRentalsIdRouteWithChildren = AppRentalsIdRoute._addFileChildren(
  AppRentalsIdRouteChildren,
)

interface AppVehiclesIdRouteChildren {
  AppVehiclesIdExpensesRoute: typeof AppVehiclesIdExpensesRoute
  AppVehiclesIdMaintenanceRoute: typeof AppVehiclesIdMaintenanceRoute
  AppVehiclesIdRentalsRoute: typeof AppVehiclesIdRentalsRoute
  AppVehiclesIdReservationsRoute: typeof AppVehiclesIdReservationsRoute
  AppVehiclesIdIndexRoute: typeof AppVehiclesIdIndexRoute
}

const AppVehiclesIdRouteChildren: AppVehiclesIdRouteChildren = {
  AppVehiclesIdExpensesRoute: AppVehiclesIdExpensesRoute,
  AppVehiclesIdMaintenanceRoute: AppVehiclesIdMaintenanceRoute,
  AppVehiclesIdRentalsRoute: AppVehiclesIdRentalsRoute,
  AppVehiclesIdReservationsRoute: AppVehiclesIdReservationsRoute,
  AppVehiclesIdIndexRoute: AppVehiclesIdIndexRoute,
}

const AppVehiclesIdRouteWithChildren = AppVehiclesIdRoute._addFileChildren(
  AppVehiclesIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersCreateRoute: typeof AppCustomersCreateRoute
  AppRentalsIdRoute: typeof AppRentalsIdRouteWithChildren
  AppRentalsInitializeRoute: typeof AppRentalsInitializeRoute
  AppReservationsIdRoute: typeof AppReservationsIdRoute
  AppReservationsCreateRoute: typeof AppReservationsCreateRoute
  AppVehiclesIdRoute: typeof AppVehiclesIdRouteWithChildren
  AppVehiclesCreateRoute: typeof AppVehiclesCreateRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppRentalsIndexRoute: typeof AppRentalsIndexRoute
  AppReservationsIndexRoute: typeof AppReservationsIndexRoute
  AppVehiclesIndexRoute: typeof AppVehiclesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersCreateRoute: AppCustomersCreateRoute,
  AppRentalsIdRoute: AppRentalsIdRouteWithChildren,
  AppRentalsInitializeRoute: AppRentalsInitializeRoute,
  AppReservationsIdRoute: AppReservationsIdRoute,
  AppReservationsCreateRoute: AppReservationsCreateRoute,
  AppVehiclesIdRoute: AppVehiclesIdRouteWithChildren,
  AppVehiclesCreateRoute: AppVehiclesCreateRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppRentalsIndexRoute: AppRentalsIndexRoute,
  AppReservationsIndexRoute: AppReservationsIndexRoute,
  AppVehiclesIndexRoute: AppVehiclesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
