/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AppVehiclesRouteRouteImport } from './routes/app/vehicles/route'
import { Route as AppReservationsRouteRouteImport } from './routes/app/reservations/route'
import { Route as AppRentalsRouteRouteImport } from './routes/app/rentals/route'
import { Route as AppCustomersRouteRouteImport } from './routes/app/customers/route'
import { Route as AppVehiclesIndexRouteImport } from './routes/app/vehicles/index'
import { Route as AppReservationsIndexRouteImport } from './routes/app/reservations/index'
import { Route as AppRentalsIndexRouteImport } from './routes/app/rentals/index'
import { Route as AppCustomersIndexRouteImport } from './routes/app/customers/index'
import { Route as AppCalendarIndexRouteImport } from './routes/app/calendar/index'
import { Route as AppVehiclesCreateRouteImport } from './routes/app/vehicles/create'
import { Route as AppVehiclesIdRouteImport } from './routes/app/vehicles/$id'
import { Route as AppReservationsCreateRouteImport } from './routes/app/reservations/create'
import { Route as AppReservationsNumberRouteImport } from './routes/app/reservations/$number'
import { Route as AppRentalsInitializeRouteImport } from './routes/app/rentals/initialize'
import { Route as AppRentalsIdRouteImport } from './routes/app/rentals/$id'
import { Route as AppCustomersCreateRouteImport } from './routes/app/customers/create'
import { Route as AppCustomersIdRouteImport } from './routes/app/customers/$id'
import { Route as AppVehiclesIdIndexRouteImport } from './routes/app/vehicles/$id/index'
import { Route as AppRentalsIdIndexRouteImport } from './routes/app/rentals/$id/index'
import { Route as AppCustomersIdIndexRouteImport } from './routes/app/customers/$id/index'
import { Route as AppVehiclesIdReservationsRouteImport } from './routes/app/vehicles/$id/reservations'
import { Route as AppVehiclesIdRepairRouteImport } from './routes/app/vehicles/$id/repair'
import { Route as AppVehiclesIdRentalsRouteImport } from './routes/app/vehicles/$id/rentals'
import { Route as AppVehiclesIdGeneralRouteImport } from './routes/app/vehicles/$id/general'
import { Route as AppVehiclesIdExpensesRouteImport } from './routes/app/vehicles/$id/expenses'
import { Route as AppRentalsIdPaymentsRouteImport } from './routes/app/rentals/$id/payments'
import { Route as AppRentalsIdDocumentsRouteImport } from './routes/app/rentals/$id/documents'
import { Route as AppCustomersIdReservationsRouteImport } from './routes/app/customers/$id/reservations'
import { Route as AppCustomersIdRentalsRouteImport } from './routes/app/customers/$id/rentals'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiclesRouteRoute = AppVehiclesRouteRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsRouteRoute = AppReservationsRouteRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRentalsRouteRoute = AppRentalsRouteRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersRouteRoute = AppCustomersRouteRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVehiclesIndexRoute = AppVehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVehiclesRouteRoute,
} as any)
const AppReservationsIndexRoute = AppReservationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReservationsRouteRoute,
} as any)
const AppRentalsIndexRoute = AppRentalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRentalsRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVehiclesCreateRoute = AppVehiclesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppVehiclesRouteRoute,
} as any)
const AppVehiclesIdRoute = AppVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVehiclesRouteRoute,
} as any)
const AppReservationsCreateRoute = AppReservationsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppReservationsRouteRoute,
} as any)
const AppReservationsNumberRoute = AppReservationsNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => AppReservationsRouteRoute,
} as any)
const AppRentalsInitializeRoute = AppRentalsInitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => AppRentalsRouteRoute,
} as any)
const AppRentalsIdRoute = AppRentalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRentalsRouteRoute,
} as any)
const AppCustomersCreateRoute = AppCustomersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const AppVehiclesIdIndexRoute = AppVehiclesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppRentalsIdIndexRoute = AppRentalsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRentalsIdRoute,
} as any)
const AppCustomersIdIndexRoute = AppCustomersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersIdRoute,
} as any)
const AppVehiclesIdReservationsRoute =
  AppVehiclesIdReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AppVehiclesIdRoute,
  } as any)
const AppVehiclesIdRepairRoute = AppVehiclesIdRepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppVehiclesIdRentalsRoute = AppVehiclesIdRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppVehiclesIdGeneralRoute = AppVehiclesIdGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppVehiclesIdExpensesRoute = AppVehiclesIdExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppRentalsIdPaymentsRoute = AppRentalsIdPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRentalsIdRoute,
} as any)
const AppRentalsIdDocumentsRoute = AppRentalsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRentalsIdRoute,
} as any)
const AppCustomersIdReservationsRoute =
  AppCustomersIdReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AppCustomersIdRoute,
  } as any)
const AppCustomersIdRentalsRoute = AppCustomersIdRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppCustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app/customers': typeof AppCustomersRouteRouteWithChildren
  '/app/rentals': typeof AppRentalsRouteRouteWithChildren
  '/app/reservations': typeof AppReservationsRouteRouteWithChildren
  '/app/vehicles': typeof AppVehiclesRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRouteWithChildren
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/rentals/$id': typeof AppRentalsIdRouteWithChildren
  '/app/rentals/initialize': typeof AppRentalsInitializeRoute
  '/app/reservations/$number': typeof AppReservationsNumberRoute
  '/app/reservations/create': typeof AppReservationsCreateRoute
  '/app/vehicles/$id': typeof AppVehiclesIdRouteWithChildren
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/rentals/': typeof AppRentalsIndexRoute
  '/app/reservations/': typeof AppReservationsIndexRoute
  '/app/vehicles/': typeof AppVehiclesIndexRoute
  '/app/customers/$id/rentals': typeof AppCustomersIdRentalsRoute
  '/app/customers/$id/reservations': typeof AppCustomersIdReservationsRoute
  '/app/rentals/$id/documents': typeof AppRentalsIdDocumentsRoute
  '/app/rentals/$id/payments': typeof AppRentalsIdPaymentsRoute
  '/app/vehicles/$id/expenses': typeof AppVehiclesIdExpensesRoute
  '/app/vehicles/$id/general': typeof AppVehiclesIdGeneralRoute
  '/app/vehicles/$id/rentals': typeof AppVehiclesIdRentalsRoute
  '/app/vehicles/$id/repair': typeof AppVehiclesIdRepairRoute
  '/app/vehicles/$id/reservations': typeof AppVehiclesIdReservationsRoute
  '/app/customers/$id/': typeof AppCustomersIdIndexRoute
  '/app/rentals/$id/': typeof AppRentalsIdIndexRoute
  '/app/vehicles/$id/': typeof AppVehiclesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/rentals/initialize': typeof AppRentalsInitializeRoute
  '/app/reservations/$number': typeof AppReservationsNumberRoute
  '/app/reservations/create': typeof AppReservationsCreateRoute
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/rentals': typeof AppRentalsIndexRoute
  '/app/reservations': typeof AppReservationsIndexRoute
  '/app/vehicles': typeof AppVehiclesIndexRoute
  '/app/customers/$id/rentals': typeof AppCustomersIdRentalsRoute
  '/app/customers/$id/reservations': typeof AppCustomersIdReservationsRoute
  '/app/rentals/$id/documents': typeof AppRentalsIdDocumentsRoute
  '/app/rentals/$id/payments': typeof AppRentalsIdPaymentsRoute
  '/app/vehicles/$id/expenses': typeof AppVehiclesIdExpensesRoute
  '/app/vehicles/$id/general': typeof AppVehiclesIdGeneralRoute
  '/app/vehicles/$id/rentals': typeof AppVehiclesIdRentalsRoute
  '/app/vehicles/$id/repair': typeof AppVehiclesIdRepairRoute
  '/app/vehicles/$id/reservations': typeof AppVehiclesIdReservationsRoute
  '/app/customers/$id': typeof AppCustomersIdIndexRoute
  '/app/rentals/$id': typeof AppRentalsIdIndexRoute
  '/app/vehicles/$id': typeof AppVehiclesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app/customers': typeof AppCustomersRouteRouteWithChildren
  '/app/rentals': typeof AppRentalsRouteRouteWithChildren
  '/app/reservations': typeof AppReservationsRouteRouteWithChildren
  '/app/vehicles': typeof AppVehiclesRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRouteWithChildren
  '/app/customers/create': typeof AppCustomersCreateRoute
  '/app/rentals/$id': typeof AppRentalsIdRouteWithChildren
  '/app/rentals/initialize': typeof AppRentalsInitializeRoute
  '/app/reservations/$number': typeof AppReservationsNumberRoute
  '/app/reservations/create': typeof AppReservationsCreateRoute
  '/app/vehicles/$id': typeof AppVehiclesIdRouteWithChildren
  '/app/vehicles/create': typeof AppVehiclesCreateRoute
  '/app/calendar/': typeof AppCalendarIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/rentals/': typeof AppRentalsIndexRoute
  '/app/reservations/': typeof AppReservationsIndexRoute
  '/app/vehicles/': typeof AppVehiclesIndexRoute
  '/app/customers/$id/rentals': typeof AppCustomersIdRentalsRoute
  '/app/customers/$id/reservations': typeof AppCustomersIdReservationsRoute
  '/app/rentals/$id/documents': typeof AppRentalsIdDocumentsRoute
  '/app/rentals/$id/payments': typeof AppRentalsIdPaymentsRoute
  '/app/vehicles/$id/expenses': typeof AppVehiclesIdExpensesRoute
  '/app/vehicles/$id/general': typeof AppVehiclesIdGeneralRoute
  '/app/vehicles/$id/rentals': typeof AppVehiclesIdRentalsRoute
  '/app/vehicles/$id/repair': typeof AppVehiclesIdRepairRoute
  '/app/vehicles/$id/reservations': typeof AppVehiclesIdReservationsRoute
  '/app/customers/$id/': typeof AppCustomersIdIndexRoute
  '/app/rentals/$id/': typeof AppRentalsIdIndexRoute
  '/app/vehicles/$id/': typeof AppVehiclesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/app/customers'
    | '/app/rentals'
    | '/app/reservations'
    | '/app/vehicles'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/'
    | '/demo'
    | '/app/customers/$id'
    | '/app/customers/create'
    | '/app/rentals/$id'
    | '/app/rentals/initialize'
    | '/app/reservations/$number'
    | '/app/reservations/create'
    | '/app/vehicles/$id'
    | '/app/vehicles/create'
    | '/app/calendar'
    | '/app/customers/'
    | '/app/rentals/'
    | '/app/reservations/'
    | '/app/vehicles/'
    | '/app/customers/$id/rentals'
    | '/app/customers/$id/reservations'
    | '/app/rentals/$id/documents'
    | '/app/rentals/$id/payments'
    | '/app/vehicles/$id/expenses'
    | '/app/vehicles/$id/general'
    | '/app/vehicles/$id/rentals'
    | '/app/vehicles/$id/repair'
    | '/app/vehicles/$id/reservations'
    | '/app/customers/$id/'
    | '/app/rentals/$id/'
    | '/app/vehicles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/signin'
    | '/auth/signup'
    | '/app'
    | '/demo'
    | '/app/customers/create'
    | '/app/rentals/initialize'
    | '/app/reservations/$number'
    | '/app/reservations/create'
    | '/app/vehicles/create'
    | '/app/calendar'
    | '/app/customers'
    | '/app/rentals'
    | '/app/reservations'
    | '/app/vehicles'
    | '/app/customers/$id/rentals'
    | '/app/customers/$id/reservations'
    | '/app/rentals/$id/documents'
    | '/app/rentals/$id/payments'
    | '/app/vehicles/$id/expenses'
    | '/app/vehicles/$id/general'
    | '/app/vehicles/$id/rentals'
    | '/app/vehicles/$id/repair'
    | '/app/vehicles/$id/reservations'
    | '/app/customers/$id'
    | '/app/rentals/$id'
    | '/app/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/app/customers'
    | '/app/rentals'
    | '/app/reservations'
    | '/app/vehicles'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/'
    | '/demo/'
    | '/app/customers/$id'
    | '/app/customers/create'
    | '/app/rentals/$id'
    | '/app/rentals/initialize'
    | '/app/reservations/$number'
    | '/app/reservations/create'
    | '/app/vehicles/$id'
    | '/app/vehicles/create'
    | '/app/calendar/'
    | '/app/customers/'
    | '/app/rentals/'
    | '/app/reservations/'
    | '/app/vehicles/'
    | '/app/customers/$id/rentals'
    | '/app/customers/$id/reservations'
    | '/app/rentals/$id/documents'
    | '/app/rentals/$id/payments'
    | '/app/vehicles/$id/expenses'
    | '/app/vehicles/$id/general'
    | '/app/vehicles/$id/rentals'
    | '/app/vehicles/$id/repair'
    | '/app/vehicles/$id/reservations'
    | '/app/customers/$id/'
    | '/app/rentals/$id/'
    | '/app/vehicles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vehicles': {
      id: '/app/vehicles'
      path: '/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rentals': {
      id: '/app/rentals'
      path: '/rentals'
      fullPath: '/app/rentals'
      preLoaderRoute: typeof AppRentalsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vehicles/': {
      id: '/app/vehicles/'
      path: '/'
      fullPath: '/app/vehicles/'
      preLoaderRoute: typeof AppVehiclesIndexRouteImport
      parentRoute: typeof AppVehiclesRouteRoute
    }
    '/app/reservations/': {
      id: '/app/reservations/'
      path: '/'
      fullPath: '/app/reservations/'
      preLoaderRoute: typeof AppReservationsIndexRouteImport
      parentRoute: typeof AppReservationsRouteRoute
    }
    '/app/rentals/': {
      id: '/app/rentals/'
      path: '/'
      fullPath: '/app/rentals/'
      preLoaderRoute: typeof AppRentalsIndexRouteImport
      parentRoute: typeof AppRentalsRouteRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/app/calendar/': {
      id: '/app/calendar/'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vehicles/create': {
      id: '/app/vehicles/create'
      path: '/create'
      fullPath: '/app/vehicles/create'
      preLoaderRoute: typeof AppVehiclesCreateRouteImport
      parentRoute: typeof AppVehiclesRouteRoute
    }
    '/app/vehicles/$id': {
      id: '/app/vehicles/$id'
      path: '/$id'
      fullPath: '/app/vehicles/$id'
      preLoaderRoute: typeof AppVehiclesIdRouteImport
      parentRoute: typeof AppVehiclesRouteRoute
    }
    '/app/reservations/create': {
      id: '/app/reservations/create'
      path: '/create'
      fullPath: '/app/reservations/create'
      preLoaderRoute: typeof AppReservationsCreateRouteImport
      parentRoute: typeof AppReservationsRouteRoute
    }
    '/app/reservations/$number': {
      id: '/app/reservations/$number'
      path: '/$number'
      fullPath: '/app/reservations/$number'
      preLoaderRoute: typeof AppReservationsNumberRouteImport
      parentRoute: typeof AppReservationsRouteRoute
    }
    '/app/rentals/initialize': {
      id: '/app/rentals/initialize'
      path: '/initialize'
      fullPath: '/app/rentals/initialize'
      preLoaderRoute: typeof AppRentalsInitializeRouteImport
      parentRoute: typeof AppRentalsRouteRoute
    }
    '/app/rentals/$id': {
      id: '/app/rentals/$id'
      path: '/$id'
      fullPath: '/app/rentals/$id'
      preLoaderRoute: typeof AppRentalsIdRouteImport
      parentRoute: typeof AppRentalsRouteRoute
    }
    '/app/customers/create': {
      id: '/app/customers/create'
      path: '/create'
      fullPath: '/app/customers/create'
      preLoaderRoute: typeof AppCustomersCreateRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/app/customers/$id': {
      id: '/app/customers/$id'
      path: '/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/app/vehicles/$id/': {
      id: '/app/vehicles/$id/'
      path: '/'
      fullPath: '/app/vehicles/$id/'
      preLoaderRoute: typeof AppVehiclesIdIndexRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/rentals/$id/': {
      id: '/app/rentals/$id/'
      path: '/'
      fullPath: '/app/rentals/$id/'
      preLoaderRoute: typeof AppRentalsIdIndexRouteImport
      parentRoute: typeof AppRentalsIdRoute
    }
    '/app/customers/$id/': {
      id: '/app/customers/$id/'
      path: '/'
      fullPath: '/app/customers/$id/'
      preLoaderRoute: typeof AppCustomersIdIndexRouteImport
      parentRoute: typeof AppCustomersIdRoute
    }
    '/app/vehicles/$id/reservations': {
      id: '/app/vehicles/$id/reservations'
      path: '/reservations'
      fullPath: '/app/vehicles/$id/reservations'
      preLoaderRoute: typeof AppVehiclesIdReservationsRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/vehicles/$id/repair': {
      id: '/app/vehicles/$id/repair'
      path: '/repair'
      fullPath: '/app/vehicles/$id/repair'
      preLoaderRoute: typeof AppVehiclesIdRepairRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/vehicles/$id/rentals': {
      id: '/app/vehicles/$id/rentals'
      path: '/rentals'
      fullPath: '/app/vehicles/$id/rentals'
      preLoaderRoute: typeof AppVehiclesIdRentalsRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/vehicles/$id/general': {
      id: '/app/vehicles/$id/general'
      path: '/general'
      fullPath: '/app/vehicles/$id/general'
      preLoaderRoute: typeof AppVehiclesIdGeneralRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/vehicles/$id/expenses': {
      id: '/app/vehicles/$id/expenses'
      path: '/expenses'
      fullPath: '/app/vehicles/$id/expenses'
      preLoaderRoute: typeof AppVehiclesIdExpensesRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/app/rentals/$id/payments': {
      id: '/app/rentals/$id/payments'
      path: '/payments'
      fullPath: '/app/rentals/$id/payments'
      preLoaderRoute: typeof AppRentalsIdPaymentsRouteImport
      parentRoute: typeof AppRentalsIdRoute
    }
    '/app/rentals/$id/documents': {
      id: '/app/rentals/$id/documents'
      path: '/documents'
      fullPath: '/app/rentals/$id/documents'
      preLoaderRoute: typeof AppRentalsIdDocumentsRouteImport
      parentRoute: typeof AppRentalsIdRoute
    }
    '/app/customers/$id/reservations': {
      id: '/app/customers/$id/reservations'
      path: '/reservations'
      fullPath: '/app/customers/$id/reservations'
      preLoaderRoute: typeof AppCustomersIdReservationsRouteImport
      parentRoute: typeof AppCustomersIdRoute
    }
    '/app/customers/$id/rentals': {
      id: '/app/customers/$id/rentals'
      path: '/rentals'
      fullPath: '/app/customers/$id/rentals'
      preLoaderRoute: typeof AppCustomersIdRentalsRouteImport
      parentRoute: typeof AppCustomersIdRoute
    }
  }
}

interface AppCustomersIdRouteChildren {
  AppCustomersIdRentalsRoute: typeof AppCustomersIdRentalsRoute
  AppCustomersIdReservationsRoute: typeof AppCustomersIdReservationsRoute
  AppCustomersIdIndexRoute: typeof AppCustomersIdIndexRoute
}

const AppCustomersIdRouteChildren: AppCustomersIdRouteChildren = {
  AppCustomersIdRentalsRoute: AppCustomersIdRentalsRoute,
  AppCustomersIdReservationsRoute: AppCustomersIdReservationsRoute,
  AppCustomersIdIndexRoute: AppCustomersIdIndexRoute,
}

const AppCustomersIdRouteWithChildren = AppCustomersIdRoute._addFileChildren(
  AppCustomersIdRouteChildren,
)

interface AppCustomersRouteRouteChildren {
  AppCustomersIdRoute: typeof AppCustomersIdRouteWithChildren
  AppCustomersCreateRoute: typeof AppCustomersCreateRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteRouteChildren: AppCustomersRouteRouteChildren = {
  AppCustomersIdRoute: AppCustomersIdRouteWithChildren,
  AppCustomersCreateRoute: AppCustomersCreateRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteRouteWithChildren =
  AppCustomersRouteRoute._addFileChildren(AppCustomersRouteRouteChildren)

interface AppRentalsIdRouteChildren {
  AppRentalsIdDocumentsRoute: typeof AppRentalsIdDocumentsRoute
  AppRentalsIdPaymentsRoute: typeof AppRentalsIdPaymentsRoute
  AppRentalsIdIndexRoute: typeof AppRentalsIdIndexRoute
}

const AppRentalsIdRouteChildren: AppRentalsIdRouteChildren = {
  AppRentalsIdDocumentsRoute: AppRentalsIdDocumentsRoute,
  AppRentalsIdPaymentsRoute: AppRentalsIdPaymentsRoute,
  AppRentalsIdIndexRoute: AppRentalsIdIndexRoute,
}

const AppRentalsIdRouteWithChildren = AppRentalsIdRoute._addFileChildren(
  AppRentalsIdRouteChildren,
)

interface AppRentalsRouteRouteChildren {
  AppRentalsIdRoute: typeof AppRentalsIdRouteWithChildren
  AppRentalsInitializeRoute: typeof AppRentalsInitializeRoute
  AppRentalsIndexRoute: typeof AppRentalsIndexRoute
}

const AppRentalsRouteRouteChildren: AppRentalsRouteRouteChildren = {
  AppRentalsIdRoute: AppRentalsIdRouteWithChildren,
  AppRentalsInitializeRoute: AppRentalsInitializeRoute,
  AppRentalsIndexRoute: AppRentalsIndexRoute,
}

const AppRentalsRouteRouteWithChildren = AppRentalsRouteRoute._addFileChildren(
  AppRentalsRouteRouteChildren,
)

interface AppReservationsRouteRouteChildren {
  AppReservationsNumberRoute: typeof AppReservationsNumberRoute
  AppReservationsCreateRoute: typeof AppReservationsCreateRoute
  AppReservationsIndexRoute: typeof AppReservationsIndexRoute
}

const AppReservationsRouteRouteChildren: AppReservationsRouteRouteChildren = {
  AppReservationsNumberRoute: AppReservationsNumberRoute,
  AppReservationsCreateRoute: AppReservationsCreateRoute,
  AppReservationsIndexRoute: AppReservationsIndexRoute,
}

const AppReservationsRouteRouteWithChildren =
  AppReservationsRouteRoute._addFileChildren(AppReservationsRouteRouteChildren)

interface AppVehiclesIdRouteChildren {
  AppVehiclesIdExpensesRoute: typeof AppVehiclesIdExpensesRoute
  AppVehiclesIdGeneralRoute: typeof AppVehiclesIdGeneralRoute
  AppVehiclesIdRentalsRoute: typeof AppVehiclesIdRentalsRoute
  AppVehiclesIdRepairRoute: typeof AppVehiclesIdRepairRoute
  AppVehiclesIdReservationsRoute: typeof AppVehiclesIdReservationsRoute
  AppVehiclesIdIndexRoute: typeof AppVehiclesIdIndexRoute
}

const AppVehiclesIdRouteChildren: AppVehiclesIdRouteChildren = {
  AppVehiclesIdExpensesRoute: AppVehiclesIdExpensesRoute,
  AppVehiclesIdGeneralRoute: AppVehiclesIdGeneralRoute,
  AppVehiclesIdRentalsRoute: AppVehiclesIdRentalsRoute,
  AppVehiclesIdRepairRoute: AppVehiclesIdRepairRoute,
  AppVehiclesIdReservationsRoute: AppVehiclesIdReservationsRoute,
  AppVehiclesIdIndexRoute: AppVehiclesIdIndexRoute,
}

const AppVehiclesIdRouteWithChildren = AppVehiclesIdRoute._addFileChildren(
  AppVehiclesIdRouteChildren,
)

interface AppVehiclesRouteRouteChildren {
  AppVehiclesIdRoute: typeof AppVehiclesIdRouteWithChildren
  AppVehiclesCreateRoute: typeof AppVehiclesCreateRoute
  AppVehiclesIndexRoute: typeof AppVehiclesIndexRoute
}

const AppVehiclesRouteRouteChildren: AppVehiclesRouteRouteChildren = {
  AppVehiclesIdRoute: AppVehiclesIdRouteWithChildren,
  AppVehiclesCreateRoute: AppVehiclesCreateRoute,
  AppVehiclesIndexRoute: AppVehiclesIndexRoute,
}

const AppVehiclesRouteRouteWithChildren =
  AppVehiclesRouteRoute._addFileChildren(AppVehiclesRouteRouteChildren)

interface AppRouteRouteChildren {
  AppCustomersRouteRoute: typeof AppCustomersRouteRouteWithChildren
  AppRentalsRouteRoute: typeof AppRentalsRouteRouteWithChildren
  AppReservationsRouteRoute: typeof AppReservationsRouteRouteWithChildren
  AppVehiclesRouteRoute: typeof AppVehiclesRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCustomersRouteRoute: AppCustomersRouteRouteWithChildren,
  AppRentalsRouteRoute: AppRentalsRouteRouteWithChildren,
  AppReservationsRouteRoute: AppReservationsRouteRouteWithChildren,
  AppVehiclesRouteRoute: AppVehiclesRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
